AWSTemplateFormatVersion: '2010-09-09'
Description: 'Family Password Manager - Main Stack'

Parameters:
  DomainName:
    Type: String
    Description: 'Your registered domain name'
    Default: 'yourdomain.com'  # REPLACE THIS

  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - prod

Resources:
  # We'll add resources in upcoming sprints
  # This is just the skeleton for now
  
  PlaceholderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Environment}-password-manager-placeholder'

Outputs:
  StackName:
    Value: !Ref AWS::StackName
    Description: 'CloudFormation stack name'